### PR TITLE
fix: use demjson3

### PR DESCRIPTION
**Pull request by amitkot**
demjson is no longer installable on systems with newer setuptools

Solves #2

### CODE REVIEW

**Comment by anki-code** [comment]
Thanks @amitkot !

**Comment by amitkot** [comment]
@anki-code could you also release a new version of xontrib-output-search that uses this fix? 🙏

**Comment by anki-code** [comment]
@amitkot You can just run `pip install -U tokenize-output` to update the module to 0.4.6 )

**Comment by amitkot** [comment]
@anki-code Ok, thanks! checked now and singe `xontrib-output-search` does not pin a specific version of tokenize-output this indeed works.

**Pull request merged**
